name: petrel_register_code_gen
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  test: ^1.24.0
