name: petrel_register_code_gen
description: Petrel通道代码生成器
version: 0.0.2
homepage: https://github.com/PetrelHotUpdate/petrel_code_gen

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  path: ^1.8.0
  analyzer: ^6.8.0
  petrel_register_code_gen_annotation: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  test: ^1.24.0
